export const AdminSignIn = {
    ADMIN_SIGNIN_REQUEST: 'ADMIN_SIGNIN_REQUEST',
    ADMIN_SIGNIN_SUCCESS: 'ADMIN_SIGNIN_SUCCESS',
    ADMIN_SIGNIN_FAILURE: 'ADMIN_SIGNIN_FAILURE',
    ADMIN_SIGNIN_RESET: 'ADMIN_SIGNIN_RESET'
}



export const PromotorType = {
    PROMOTOR_TYPE_REQUEST: 'PROMOTOR_TYPE_REQUEST',
    PROMOTOR_TYPE_SUCCESS: 'PROMOTOR_TYPE_SUCCESS',
    PROMOTOR_TYPE_FAILURE: 'PROMOTOR_TYPE_FAILURE',
    PROMOTOR_TYPE_RESET: 'PROMOTOR_TYPE_RESET'
}

// admin order
export const AdminOrder = {
    // change number
    ADMIN_ORDER_CHANGE_NUMBER: 'ADMIN_ORDER_CHANGE_NUMBER',
    // admin order
    ADMIN_ORDER_REQUEST: 'ADMIN_ORDER_REQUEST',
    ADMIN_ORDER_SUCCESS: 'ADMIN_ORDER_SUCCESS',
    ADMIN_ORDER_FAILURE: 'ADMIN_ORDER_FAILURE',
    // By id
    ADMIN_ORDER_BY_ID_REQUEST: 'ADMIN_ORDER_BY_ID_REQUEST',
    ADMIN_ORDER_BY_ID_SUCCESS: 'ADMIN_ORDER_BY_ID_SUCCESS',
    ADMIN_ORDER_BY_ID_FAILURE: 'ADMIN_ORDER_BY_ID_FAILURE',
    
}



// Combos
export const ComboProducts = {
    // change number
    COMBO_ADMIN_PRODUCTS_CHANGE: 'COMBO_ADMIN_PRODUCTS_CHANGE',
    // list combos
    COMBO_ADMIN_PRODUCTS_REQUEST: 'COMBO_ADMIN_PRODUCTS_REQUEST',
    COMBO_ADMIN_PRODUCTS_SUCCESS: 'COMBO_ADMIN_PRODUCTS_SUCCESS',
    COMBO_ADMIN_PRODUCTS_FAILURE: 'COMBO_ADMIN_PRODUCTS_FAILURE',

    // landing get combo
    COMBO_LANDING_REQUEST: 'COMBO_LANDING_REQUEST',
    COMBO_LANDING_SUCCESS: 'COMBO_LANDING_SUCCESS',
    COMBO_LANDING_FAILURE: 'COMBO_LANDING_FAILURE',

}



// Types User

export const UserSignIn = {
    USER_SIGNIN_REQUEST: 'USER_SIGNIN_REQUEST',
    USER_SIGNIN_SUCCESS: 'USER_SIGNIN_SUCCESS',
    USER_SIGNIN_FAILURE: 'USER_SIGNIN_FAILURE',
    USER_SIGNIN_RESET: 'USER_SIGNIN_RESET',
}


export const UserUpdateType = {
    USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
    USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    USER_UPDATE_FAILURE: 'USER_UPDATE_FAILURE',
}