export const AdminSignIn={
    ADMIN_SIGNIN_REQUEST:'ADMIN_SIGNIN_REQUEST',
    ADMIN_SIGNIN_SUCCESS:'ADMIN_SIGNIN_SUCCESS',
    ADMIN_SIGNIN_FAILURE:'ADMIN_SIGNIN_FAILURE',
    ADMIN_SIGNIN_RESET:'ADMIN_SIGNIN_RESET'
}

export const UserSignIn={
    USER_SIGNIN_REQUEST:'USER_SIGNIN_REQUEST',
    USER_SIGNIN_SUCCESS:'USER_SIGNIN_SUCCESS',
    USER_SIGNIN_FAILURE:'USER_SIGNIN_FAILURE',
    USER_SIGNIN_RESET:'USER_SIGNIN_RESET'
}