export const AdminSignIn={
    ADMIN_SIGNIN_REQUEST:'ADMIN_SIGNIN_REQUEST',
    ADMIN_SIGNIN_SUCCESS:'ADMIN_SIGNIN_SUCCESS',
    ADMIN_SIGNIN_FAILURE:'ADMIN_SIGNIN_FAILURE',
    ADMIN_SIGNIN_RESET:'ADMIN_SIGNIN_RESET'
}